version: '2'
services:
  # 基本环境
  service: # 容器名字
    # build 该置顶目录下的dockerfile
    build: .
    # image指定build Dockerfile生成镜像的名称
    image: utf8
    ports:
      - 9999:80
    volumes:
        # 挂载的 Flag
        - "$PWD/flag:/flag"
    tty: true
    networks:
      - net

networks:
    # 配置docker network
    net:
      external:
         name: h1ve_frp_containers
