version: "2"
services:
  web:
    build: .
    image: easycalc
    ports:
      - 9999:8000
    volumes:
      - "$PWD/flag:/flag"
    networks:
      - net

networks:
    # 配置docker network
    net:
      external:
         name: h1ve_frp_containers